---
version: 0.1.0
alias: latest_working_file
discoveryPort:
  name: new_working_manifest
  shortDescription: shortDescription
  longDescription: longDescription
  tags: []
  industryDomain: industryDomain
  function: functionLabel
  regulatoryFields:
    dataPrivacy: public
    customerInfo: PII
    dataOrigin: humanGenerated
    monetaryInfo: financialData
  dataTimeRange:
    fromMinDataDate: '123456789'
    toMinDataDate: '987654321'
    timeColumn: 'timeColumn'
  category: customer
  image: http://google.com
inputPorts:
  - alias: car_input_port
    type: s3-csv
    syncType: pull
    dataSetUrn: urn:dv:dataset:2ecc1598-0c68-4e1f-a56d-70440f5d4790
    description: inputPortDescription
    filter: 'inputPortFilter'
    projection:
        - legal_entity
        - store_name
        - amount
        - payment_option
        - currency
    entity:
      path: "s3://##my_bucket_name##/sample-data/inputData/incr emental/payLoad_##my_dynamic_year##/*.##my_extension##"
      variables:
        - key: my_dynamic_year
          value: date-YYYYMMdd
        - key: my_bucket_name
          value: dataverse-byte
        - key: my_extension
          value: "csv"
    incrementalLoad: true
    incrementalStrategy:
        frequency:
          - keyReference : my_dynamic_year
            mode: range
            interval : -1
          - keyReference : my_bucket_name
            mode: absolute
            interval : 9999
          - keyReference : my_extension
            mode: range
            interval : -12345
  - alias: rental_input_port
    type: s3-csv
    syncType: pull
    dataSetUrn: urn:dv:dataset:5910acab-69a2-477c-89ce-bda36fe32544
    description: inputPortDescription
    filter: 'inputPortFilter'
    projection:
        - legal_entity
        - store_name
        - amount
        - payment_option
        - currency
    entity:
      path: "s3://##my_bucket_name##/sample-data/inputData/incr emental/payLoad_##my_dynamic_year##/*.##my_extension##"
      variables:
        - key: my_dynamic_year
          value: date-YYYYMMdd
        - key: my_bucket_name
          value: dataverse-byte
        - key: my_extension
          value: "csv"
  - alias: data_product_as_source
    type: dataproduct
    syncType: pull
    description: string
    dataProductUrn: urn:dv:dataproduct:10e124d2-4621-47de-9cf1-3e35010cec96
    filter: ""
    projection:
      - id
      - name
      - marks
      - modified
productState:
  retentionVersions: "retentionVersions"
  retentionPeriod: "retentionPeriod"
  refreshInterval: "*/10 * * * *"
  updateStrategy: "scd2"
  updateStrategyOptions:
    processingTimeColumn: ["processingTimeColumn"]
    actualTimeColumn: "actualTimeColumn"
    timeTrackingColumn: "timeTrackingColumn"
    uniqueKeyColumns: ["Unique", "Key", "Columns"]
    changeTrackingColumns: ["Change", "Track", "Columns"]
  logicalSchema:
    properties:
      legal_entity:
        type: string
      store_name:
        type: string
      amount:
        type: int
      payment_option:
        type: string
      currency:
        type: string
transformation:
- alias: Transform1
  sequenceNo: '1'
  type: SQL
  description: Join input1 and input2 to get the actual member name
  query: select * from i1 inner join i2 on i1.id=i2.id
  references:
  - alias: car_input_port
    sqlReference: i1
  - alias: rental_input_port
    sqlReference: i2
  - alias: data_product_as_source
    sqlReference: i2i2i2i2i2i2i2i2i2i2ii2i2i2i2i2i2i2i2i2i2i2i2i2i2ii2i2i2i2i2i2i2i2i2i2i2i2i2i2ii2i2i2i2i2i2i2i2i2i2i2i2i2i2ii2i2i2i2i2i2i2i2i2i2i2i2i2i2ii2i2i2i2
- alias: Transform2
  sequenceNo: '2'
  type: SQL
  description: Generate the sum of marks on a name level
  query: select name,sum(marks) from t1 group by name
  references:
  - alias: rental_input_port
    sqlReference: t1
- alias: Transform3
  sequenceNo: '3'
  type: SQL
  description: Generate the sum of marks on a name level
  query: select name,sum(marks) from t1 group by name 
outputPort:
  subscriptionChannels:
    - channelType: REST-API
      queryType: SQL
    - channelType: JDBC
      queryType: SQL
controlPort:
  dataQualityRules:
    RecordCountCheck:
      inputPort:
        - referenceAlias: car_input_port
          expression: ">="
          number: 100
      productState:
        referenceAlias: car_input_port
        expression: ==
        number: 100
    NullValueCheck:
      inputPort:
        - referenceAlias: car_input_port
          checks:
            - column: amount
              expression: ">="
              number: 9
            - column: payment_option
              expression: ">="
              number: 8
      productState:
        referenceAlias: car_input_port
        checks:
          - column: amount
            expression: ">="
            number: 0.9
    NullCombinationCheck:
      productState:
        referenceAlias: car_input_port
        checks:
          - columns:
              - transaction_reference
              - order_reference
            expression: ">="
            number: 0.99
    UnacceptableTextValueCheck:
      inputPort:
        - referenceAlias: car_input_port
          checks:
            - column: payment_option
              valueList:
                - VISA
                - MASTERCARD
              number: 0.95
              expression: ">="
      productState:
        referenceAlias: car_input_port
        checks:
          - column: payment_option
            valueList:
              - MASTERCARD
              - VISA
            number: 0.9
            expression: ">="
    UniquenessCheck:
      inputPort:
        - referenceAlias: car_input_port
          checks:
            - column: store_group_name
            - column: store_name
    UniqueCombinationCheck:
      inputPort:
        - referenceAlias: car_input_port
          checks:
            - columns:
                - store_name
                - transaction_Reference
      productState:
        referenceAlias: car_input_port
        checks:
          - columns:
              - store_name
              - transaction_Reference
    DistinctValueCountCheck:
      inputPort:
        - referenceAlias: car_input_port
          checks:
            - column: payment_option
              number: 2
              expression: "<="
      productState:
        referenceAlias: car_input_port
        checks:
          - column: payment_option
            number: 2
            expression: "<="
